version: '3'
services:
  app:
    restart: always
    build: .
    network_mode: host
    command: $DOCKER_APP_CMD
    depends_on:
      - db

  db:
    image: mongo:latest
    restart: always
    volumes:
      - dbvolume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_DB
    ports:
      - $MONGO_PORT:$MONGO_PORT
    command: mongod --port $MONGO_PORT


volumes:
  dbvolume: